### ISSUE TITLE
Choose a better username please.

### ISSUE THREAD

**Issue by abhi18av** [sharma-shruti/My_Articles#1]
@shruti8873 doesn't sound too reflective of your personality. Maybe try and pick something like 
`shruti-sharma` or `shruti_sharma` etc. 

In case it's not available, keep looking for a better one. Trust me, this will be handy later on.

**Comment by abhi18av** [comment]
Please resolve this issue, once you've updated your username.

**Comment by sharma-shruti** [comment]
Changed it to sharma-shruti

**Comment by abhi18av** [comment]
Yup, a definite improvement!
