### ISSUE TITLE
Add content to the first article

### ISSUE THREAD

**Issue by abhi18av** [sharma-shruti/My_Articles#3]
@shruti8873 , please flesh out the article.

Some tips

1. Don't be a perfectionist.
2. Make it a habit of commiting frequently - as in after every paragraph.
3. Try and use some formatting in `markdown mentioned here https://github.com/shruti8873/My_Articles/pull/2#issuecomment-593063331

**Comment by abhi18av** [comment]
NOTE:  If you go to the Pull Request https://github.com/shruti8873/My_Articles/pull/2  you'll see the following 

<img width="778" alt="image" src="https://user-images.githubusercontent.com/12799326/75621221-af839380-5bb7-11ea-9bee-a19f226c8e95.png">

Github does that to correlate the pieces of information scattered around in a `repository`

**Comment by abhi18av** [comment]
@sharma-shruti 
I've created a change in the repository by renaming the file extension. This is, in effect, negligible change.

But now, you have the opportunity to use `git pull` and practice things like `rebase`

**Comment by abhi18av** [comment]
@sharma-shruti please feel free to close this, as you've made progress.

For future reference, please either ask @arushi-bhatt or @abhi18av  to review you pull requests. A lot of practice learning happens through code reviews.

**Comment by sharma-shruti** [comment]
Okay, got it.
